#!/bin/sh

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl spawn "foot --server"
riverctl spawn "emacs --daemon"

riverctl map normal Super R spawn fuzzel
riverctl map normal Super T spawn footclient
riverctl map normal Super F spawn Thunar
riverctl map normal Super S spawn screenshot
riverctl map normal Super Return spawn "emacsclient -c"

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super N focus-view next
riverctl map normal Super D focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift D swap previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super BackSpace zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl map normal Super ampersand set-focused-tags 1
riverctl map normal Super+Shift ampersand set-view-tags 1

riverctl map normal Super bracketleft set-focused-tags 2
riverctl map normal Super+Shift bracketleft set-view-tags 2

riverctl map normal Super braceleft set-focused-tags 4
riverctl map normal Super+Shift braceleft set-view-tags 4

riverctl map normal Super braceright set-focused-tags 8
riverctl map normal Super+Shift braceright set-view-tags 8

riverctl map normal Super parenleft set-focused-tags 16
riverctl map normal Super+Shift parenleft set-view-tags 16

# Super+Space to toggle float
riverctl map normal Super+Shift Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super Space toggle-fullscreen

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x334155
riverctl border-color-unfocused 0x020617

# Set keyboard repeat rate
riverctl set-repeat 50 300
riverctl keyboard-layout -variant 'dvp,ThaiMnc' -options 'grp:ctrl_space_toggle,caps:escape' 'us,th'
#riverctl keyboard-layout -variant 'dvp' 'us'

# Auto starting apps
bash $HOME/.config/river/autostart.sh

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 1 -outer-padding 1 &
exec dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
